# #
#   @type               github workflow
#   @desc               manually activated workflow to remove issue labels
#   @author             Aetherinox
#   @url                https://github.com/Aetherinox
#
#   @notes              This Github action must be activated manually.  This workflow script will do the following:
#                           - Remove all existing labels in repository
#
#   @secrets            secrets.SELF_TOKEN                                          self github personal access token (fine-grained)
#                       secrets.SELF_TOKEN_CL                                       self github personal access token (classic)
#                       secrets.NPM_TOKEN                                           self npmjs access token
#                       secrets.PYPI_API_TOKEN                                      self Pypi API token (production site) - https://pypi.org/
#                       secrets.PYPI_API_TEST_TOKEN                                 self Pypi API token (test site) - https://test.pypi.org/
#                       secrets.SELF_DOCKERHUB_TOKEN                                self Dockerhub token
#                       secrets.ORG_TOKEN                                           org github personal access token (fine-grained)
#                       secrets.ORG_TOKEN_CL                                        org github personal access token (classic)
#                       secrets.ORG_DOCKERHUB_TOKEN                                 org dockerhub secret
#                       secrets.ORG_GITEA_TOKEN                                     org gitea personal access token (classic) with package:write permission
#                       secrets.BOT_GPG_KEY_ASC                                     bot gpg private key (armored) | BEGIN PGP PRIVATE KEY BLOCK
#                       secrets.BOT_GPG_PASSPHRASE                                  bot gpg private key passphrase
#                       secrets.DISCORD_WEBHOOK_CHAN_GITHUB_RELEASES                discord webhook to report release notifications from github to discord
#                       secrets.DISCORD_WEBHOOK_CHAN_GITHUB_WORKFLOWS               discord webhook to report workflow notifications from github to discord
#                       secrets.DISCORD_WEBHOOK_CHAN_GITHUB_UPDATES                 discord webhook to report activity notifications from github to discord
#
#   @local              these workflows can be tested locally through the use of `act`
#                           https://github.com/nektos/act
#                       Extract act to folder
#                       Add system env var with path to act.exe
#                       Run the commands:
#                           git pull https://github.com/username/repo
#                           act -W .github/workflows/labels-clean.yml -P ubuntu-latest=catthehacker/ubuntu:full-22.04
#                           act -W .github/workflows/labels-clean.yml -s TOKEN_CL=XXXXXXXXXX --pull=false
# #

name: 'ðŸ§¹ Labels â€º Clean'
run-name: 'ðŸ§¹ Labels â€º Clean'

# #
#   triggers
# #

on:
    workflow_dispatch:

# #
#   environment variables
# #

env:
    ASSIGN_USER:                    Aetherinox
    BOT_NAME_1:                     EuropaServ
    BOT_NAME_2:                     BinaryServ
    BOT_NAME_DEPENDABOT:            dependabot[bot]
    BOT_NAME_RENOVATE:              renovate[bot]

    LABELS_JSON: |
      [
          { "name": "bug",                          "color": "8F1784", "description": "Default github label" },
          { "name": "documentation",                "color": "8F1784", "description": "Default github label" },
          { "name": "duplicate",                    "color": "8F1784", "description": "Default github label" },
          { "name": "enhancement",                  "color": "8F1784", "description": "Default github label" },
          { "name": "good first issue",             "color": "8F1784", "description": "Default github label" },
          { "name": "help wanted",                  "color": "8F1784", "description": "Default github label" },
          { "name": "invalid",                      "color": "8F1784", "description": "Default github label" },
          { "name": "question",                     "color": "8F1784", "description": "Default github label" },
          { "name": "wontfix",                      "color": "8F1784", "description": "Default github label" },
          { "name": "AC â€º Changes Made",            "color": "8F1784", "description": "Requested changes have been made and are pending a re-scan" },
          { "name": "AC â€º Changes Required",        "color": "8F1784", "description": "Requires changes to be made to the package before being accepted" },
          { "name": "AC â€º Failed",                  "color": "a61f2d", "description": "Autocheck failed to run through a complete cycle, requires investigation" },
          { "name": "AC â€º Needs Rebase",            "color": "8F1784", "description": "Due to the permissions on the requesting repo, this pull request must be rebased by the author" },
          { "name": "AC â€º Passed",                  "color": "146b4a", "description": "Ready to be reviewed" },
          { "name": "AC â€º Review Required",         "color": "8F1784", "description": "PR needs to be reviewed by another person, after the requested changes have been made" },
          { "name": "AC â€º Security Warning",        "color": "761620", "description": "Does not conform to developer policies, or includes potentially dangerous code" },
          { "name": "AC â€º Skipped Scan",            "color": "8F1784", "description": "Author has skipped code scan" },
          { "name": "Status â€º Duplicate",           "color": "75536b", "description": "Issue or pull request already exists" },
          { "name": "Status â€º Accepted",            "color": "2e7539", "description": "This pull request has been accepted" },
          { "name": "Status â€º Autoclosed",          "color": "3E0915", "description": "Originally stale and was autoclosed for no activity" },
          { "name": "Status â€º Denied",              "color": "ba4058", "description": "Pull request has been denied" },
          { "name": "Status â€º Locked",              "color": "550F45", "description": "Automatically locked by AdminServ for a prolonged period of inactivity" },
          { "name": "Status â€º Need Info",           "color": "2E3C4C", "description": "Not enough information to resolve" },
          { "name": "Status â€º No Action",           "color": "030406", "description": "Closed without any action being taken" },
          { "name": "Status â€º Pending",             "color": "984b12", "description": "Pending pull request" },
          { "name": "Status â€º Released",            "color": "1b6626", "description": "Issues or PR has been implemented and is now live" },
          { "name": "Status â€º Reopened",            "color": "8a6f14", "description": "A previously closed PR which has been re-opened" },
          { "name": "Status â€º Review",              "color": "9e1451", "description": "Currently pending review" },
          { "name": "Status â€º Stale",               "color": "928282", "description": "Has not had any activity in over 30 days" },
          { "name": "Type â€º Bug",                   "color": "9a2c2c", "description": "Something isn't working" },
          { "name": "Type â€º Dependency",            "color": "243759", "description": "Item is associated to dependency" },
          { "name": "Type â€º Docs",                  "color": "0e588d", "description": "Improvements or modifications to docs" },
          { "name": "Type â€º Feature",               "color": "3c4e93", "description": "Feature request" },
          { "name": "Type â€º Git Action",            "color": "030406", "description": "GitHub Action / workflow" },
          { "name": "Type â€º Pull Request",          "color": "8F1784", "description": "Normal pull request" },
          { "name": "Type â€º Roadmap",               "color": "8F1784", "description": "Feature or bug currently planned for implementation" },
          { "name": "Type â€º Internal",              "color": "A51994", "description": "Assigned items are for internal developer use" },
          { "name": "Build â€º Desktop",              "color": "c7ca4a", "description": "Specific to desktop" },
          { "name": "Build â€º Linux",                "color": "c7ca4a", "description": "Specific to Linux" },
          { "name": "Build â€º MacOS",                "color": "c7ca4a", "description": "Specific to MacOS" },
          { "name": "Build â€º Mobile",               "color": "c7ca4a", "description": "Specific to mobile" },
          { "name": "Build â€º Web",                  "color": "c7ca4a", "description": "Specific to web" },
          { "name": "Build â€º Windows",              "color": "c7ca4a", "description": "Specific to Windows" },
          { "name": "â€º API",                        "color": "F99B50", "description": "Plugin API, CLI, browser JS API" },
          { "name": "â€º Auto-type",                  "color": "9141E0", "description": "Auto-type functionality in desktop apps" },
          { "name": "â€º Browser",                    "color": "9141E0", "description": "Browser plugins and passing data to <=> from app" },
          { "name": "â€º Customization",              "color": "E3F0FC", "description": "Customizations: plugins, themes, configs" },
          { "name": "â€º Design",                     "color": "FA70DE", "description": "Design related queries" },
          { "name": "â€º Dist",                       "color": "FA70DE", "description": "Installers and other forms of software distribution" },
          { "name": "â€º Enterprise",                 "color": "11447a", "description": "Issues about collaboration, administration, and so on" },
          { "name": "â€º Hardware",                   "color": "5a7503", "description": "YubiKey, other tokens, biometrics" },
          { "name": "â€º Import/Export",              "color": "F5FFCC", "description": "Import from and export to different file formats" },
          { "name": "â€º Improvement",                "color": "185c98", "description": "Enhance an existing feature" },
          { "name": "â€º Performance",                "color": "006b75", "description": "Web and desktop performance issues" },
          { "name": "â€º Plugin Request",             "color": "FCE9CA", "description": "Requested changes should be implemented as a plugin" },
          { "name": "â€º Security",                   "color": "F75D39", "description": "Security issues" },
          { "name": "â€º Self-Hosting",               "color": "fad8c7", "description": "Self-hosting installations and configs" },
          { "name": "â€º Storage",                    "color": "5319e7", "description": "Storage providers: Dropbox, Google, WebDAV, etc." },
          { "name": "â€º Updater",                    "color": "1BADDE", "description": "Auto-updater issues" },
          { "name": "â€º UX",                         "color": "1BADDE", "description": "UX and usability" },
          { "name": "â€º Website",                    "color": "fef2c0", "description": "Website related issues" },
          { "name": "âš  Urgent",                     "color": "a8740e", "description": "Requires urgent attention" },
          { "name": "âš  Announcement",               "color": "DB4712", "description": "Announcements" },
          { "name": "ðŸ“° Progress Report",           "color": "392297", "description": "Development updates" },
          { "name": "ðŸ“¦ Release",                   "color": "277542", "description": "Release announcements" },
          { "name": "âœ”ï¸ Poll",                      "color": "972255", "description": "Community polls" },
          { "name": "â” Question",                  "color": "FFFFFF", "description": "All questions" }
      ]

# #
#   jobs
# #

jobs:

    # #
    #   Job â€º Remove Labels
    #
    #   This job removes all existing labels
    # #

    issues-labels-clean:
        name: >-
            ðŸ§¹ Labels â€º Clean
        runs-on: ubuntu-latest
      # runs-on: apollo-x64
        timeout-minutes: 3
        permissions:
            contents: 'read'
            id-token: 'write'
            issues: 'write'
        steps:

            # #
            #   Labels â€º Start
            # #

            - name: >-
                  âœ… Start
              id: task_label_remove_start
              run: |
                  echo "Starting workflow"

            # #
            #   Labels â€º Set Env Variables
            # #

            - name: >-
                  ðŸ•› Get Timestamp
              id: task_label_set_timestamp
              run: |
                  echo "YEAR=$(date +'%Y')" >> $GITHUB_ENV
                  echo "NOW=$(date +'%m-%d-%Y %H:%M:%S')" >> $GITHUB_ENV
                  echo "NOW_SHORT=$(date +'%m-%d-%Y')" >> $GITHUB_ENV
                  echo "NOW_LONG=$(date +'%m-%d-%Y %H:%M')" >> $GITHUB_ENV
                  echo "NOW_DOCKER_LABEL=$(date +'%Y%m%d')" >> $GITHUB_ENV

            # #
            #   Labels â€º Checkout
            # #

            - name: >-
                  â˜‘ï¸ Checkout
              id: task_label_remove_checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            # #
            #   Labels â€º Start
            # #

            - name: >-
                  ðŸ·ï¸ Delete Existing Labels
              id: task_label_remove_run
              uses: actions/github-script@v7
              with:
                  github-token: ${{ secrets.ADMINSERV_TOKEN_CL || github.token }}
                  script: |
                      const targetOwner = context.repo.owner;
                      const targetRepo = context.repo.repo;

                      // Fetch labels from the source repository
                      const response = await github.rest.issues.listLabelsForRepo({
                          owner: targetOwner,
                          repo: targetRepo,
                      });
                      console.log("Labels fetched: ", response.data);

                      const labels = response.data;
                      if (labels.length === 0) {
                          console.log("No labels found in the source repository.");
                      }

                      // Fetch all labels from the target repository and delete them
                      const existingLabels = await github.rest.issues.listLabelsForRepo({
                          owner: targetOwner,
                          repo: targetRepo,
                      });

                      // const labels = JSON.parse( process.env.LABELS_JSON );
                      let result = Object.keys(labels).length;
                      for ( const label of labels )
                      {
                          try
                          {
                              await github.rest.issues.deleteLabel(
                              {
                                  owner:        context.repo.owner,
                                  repo:         context.repo.repo,
                                  name:         label.name,
                              });
                          }
                          catch ( err )
                          {
                            console.error("Error: " + err);
                          }
                      }

                      console.log("[Success]: Added " + result + " labels to repo");

                      return result

            # #
            #   Labels â€º Get Weekly Commits
            # #

            - name: >-
                ðŸ•› Get Weekly Commit List
              id: task_label_set_weekly_commit_list
              run: |
                  echo 'WEEKLY_COMMITS<<EOF' >> $GITHUB_ENV
                  git log --format="[\`%h\`](${{ github.server_url }}/${{ github.repository }}/commit/%H) %s - %an" --since=7.days >> $GITHUB_ENV
                  echo 'EOF' >> $GITHUB_ENV
